# Generated by Django 5.2 on 2025-04-09 16:34

import django.db.models.deletion
import django.utils.timezone
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id_shoes', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sh_name', models.CharField(max_length=255)),
                ('sh_model', models.CharField(max_length=255)),
                ('sh_size', models.IntegerField(default=38)),
                ('sh_color', models.CharField(max_length=255)),
                ('sh_manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('sh_count', models.IntegerField(default=1)),
                ('sh_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sh_gender', models.CharField(blank=True, choices=[('female', 'FEMALE'), ('male', 'MALE'), ('boy', 'BOY'), ('girl', 'GIRL')], default=main.models.Shoe_gender['FEMALE'], max_length=45)),
            ],
            options={
                'db_table': 'shoes',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=main.models.shoes_image_upload_to)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.shoes')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('o_count', models.IntegerField(default=1, verbose_name='Count')),
                ('o_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('o_recipient_first_name', models.CharField(default='Name', max_length=45, verbose_name='Recipient name')),
                ('o_recipient_last_name', models.CharField(default='Surname', max_length=45, verbose_name='Recipient surname')),
                ('o_address', models.CharField(default='Address', max_length=100, verbose_name='Address')),
                ('o_email', models.CharField(default='Email', max_length=100, verbose_name='Email')),
                ('o_phone_number', models.CharField(default='Phone Number', max_length=13, verbose_name='Phone Number')),
                ('o_comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comment')),
                ('o_status', models.CharField(choices=[('accepted', 'ACCEPTED'), ('paid', 'PAID'), ('in processing', 'IN_PROCESSING'), ('delivered', 'delivered')], default='accepted', max_length=45, verbose_name='Order Status')),
                ('o_date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('o_user', models.ForeignKey(db_column='o_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('o_shoes', models.ForeignKey(db_column='o_shoes', on_delete=django.db.models.deletion.DO_NOTHING, to='main.shoes', verbose_name='Shoes')),
            ],
            options={
                'verbose_name': 'Order',
                'db_table': 'orders',
            },
        ),
    ]
