# Generated by Django 5.2 on 2025-05-27 13:26

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id_collection', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=100)),
                ('c_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='shoes',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sh_collection', to='main.collection'),
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_image', models.FileField(upload_to=main.models.collections_image_upload_to)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_images', to='main.collection')),
            ],
        ),
    ]
