# Generated by Django 5.2 on 2025-05-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_collection_shoes_collection_collectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='c_slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='shoes',
            name='sh_slug',
            field=models.SlugField(default=''),
        ),
    ]
